<ul>
<li>Version: 1.7.2 - July, 2011
  <ul>
  <li>More Fixes to the list view.</li>
  </ul>
</li>
<li>Version: 1.7.2 - July, 2011
  <ul>
  <li>Fixes to the list view.</li>
  </ul>
</li>
<li>Version: 1.7.1 - July, 2011
  <ul>
  <li>The unique_only parameter now defaults to &quot;off&quot; for all views.</li>
  <li>Adds the displayforday parameter to the upcominglist view.</li>
  </ul>
</li>
<li>Version: 1.7 - June, 2011
  <ul>
  <li>Adds the ability to filter the &quot;myevents&quot; view by a category.</li>
  </ul>
</li>
<li>Version: 1.6.1 - April, 2011
  <ul>
    <li>Remove debug statements.</li>
  </ul>
</li>
<li>Version: 1.6 - April, 2011
  <ul>
    <li>Adds a company directory field type.</li>
    <li>Bug Fixes.</li>
  </ul>
</li>
<li>Version: 1.5.7 - September 2010
  <ul>
    <li>More fixes to displaycalendar and displayupcominglist.</li>
  </ul>
</li>
<li>Version: 1.5.6 - September 2010
  <ul>
    <li>Fixes to upcoming list pagination.</li>
    <li>Fixes to unique only param in upcoming list.</li>
  </ul>
</li>
<li>Version: 1.5.5 - August 2010
  <ul>
    <li>Now Require CGExtensions 1.19.4</li>
    <li>Adds a preference for the URL prefix.</li>
    <li>Adds a preference to default new events to all day events.</li>
    <li>Adds a preference for the default start time for non-allday events.</li>
  </ul>
</li>
<li>Version: 1.5.4 - August 2010
  <ul>
    <li>Bug fixes.</li>
  </ul>
</li>
<li>Version: 1.5.3 - July 2010
  <ul>
    <li>Minor bug fix.</li>
  </ul>
</li>
<li>Version: 1.5.2 - April 2010
  <ul>
    <li>Remove leftover debug statements.</li>
  </ul>
</li>
<li>Version: 1.5.1 - April 2010
  <ul>
    <li>Bug fixes.</li>
  </ul>
</li>
<li>Version: 1.5 - April 2010
  <ul>
    <li>Adds the ability to perform search on custom field values.</li>
  </ul>
</li>
<li>Version: 1.4 - April 2010
  <ul>
    <li>Bug fixes wrt deleting events.</li>
    <li>Adds the ability for logged in frontend users to add, edit, or delete calendar events.</li>
  </ul>
</li>
<li>Version: 1.3.1 - March 2010
  <ul>
    <li>Minor bugfix in installer.</li>
  </ul>
</li>
<li>Version: 1.3 - December 2009
  <ul>
    <li>Adds the concept of all day events.</li>
    <li>Adds the ability to allow events to overlap or not.</li>
    <li>Adds the ability to remove all conflicting/overlapping events.</li>
    <li>Various bug fixes.</li>
  </ul>
</li>
<li>Version: 1.2.5 - September 2009
  <ul>
    <li>Minor bug fixes.</li>
  </ul>
</li>

<li>Version: 1.2.4 - September 2009
  <ul>
    <li>Adds support for textarea fields.</li>
    <li>Minor bug fixes.</li>
  </ul>
</li>
<li>Version: 1.2.3 - September 2009
  <ul>
    <li>Fixes stupid errors with the installer.</li>
    <li>Adds unique_only parameter.</li>
    <li>Adds basic ical support in event views.(Ted)</li>
    <li>Minor bug fixes.</li>
  </ul>
</li>
<li>Version: 1.2.2 - May 2009
  <ul>
    <li>Fixes edge case problem with dates recurring monthly on the Nth weekday</li>
    <li>Fixes upcominglist view.</li>
  </ul>
</li>
<li>Version: 1.2.1 - May 2009
  <ul>
    <li>Fixes problem with dates recurring monthly on the Nth weekday</li>
  </ul>
</li>
<li>Version: 1.2 - April 2009
  <ul>
    <li>Adds pagination to upcoming list view.</li>
    <li>Various bug fixes.</li>
  </ul>
</li>
<li>Version: 1.1 - March 2009
 <ul>
   <li>Minor bug fixes.</li>
   <li>Add enhanced monthly recuring event capabilities.</li>
   <li>Add search form.</li>
 </ul>
</li>
<li><p>Version: 1.0</p>
<p>Fork version 0.8.2 of the Calendar module, and completely re-do event adding, editing, recurring events, and templates.  This module is not comptible with previous versions of the Calendar module</p>
</li>
<li><p>Version: 0.8.2</p>
  <p>Fix to pretty urls.</p>
</li>
<li><p>Version: 0.8.1</p>
  <p>Minor fix to search integration when updating an event.</p>
  <p>Add categories information to the list display.</p>
</li>
<li><p>Version: 0.8</p>
  <p>Adds search capabilities</p>
</li>
<li><p>Version: 0.7.14</p>
  <p>Fixes a serious issue that could result in thousands of needless calendar entries being inserted into the table.</p>
</li>
<li><p>Version: 0.7.13</p>
  <p>Fixes friendly urls for detail articles</p>
</li>
<li><p>Version: 0.7.12</p>
  <p>Fixes file upload fields</p>
  <p>Fixes issues with references to the Album module</p>
  <p>Adds recurring events</p>
</li>
<li><p>Version: 0.7.11</p>
  <p>Fixed a bug introduced by brining in the categories, whereby the join did not work on earlier versions on mySQL. (codepoet)</p>
  <p>Added a list of categories that each event is associated with to the data available to the template. (codepoet)</p>
  <p>Fixed a bug introduced in 0.7.10 that prevents a clean install from working, because of an extra comma on the end of the field list for table cms_module_ecalander_event_field_values (codepoet)</p>
</li>
<li><p>Version: 0.7.10 - calguy1000</p>
<p>Added support for file uploads in custom fields</p>
<p>Added the ability to supply \'next\' as the event_id in the event display, to display the next upcoming event.</p>
</li>
<li><p>Version: 0.7.9</p>
  <p>Added custom fields that can be associated with each event.</p>
</li>

<li><p>Version: 0.7.8</p>
  <p>Fixed a detailpage/returnlink bug... again...</p>
</li>

<li><p>Version: 0.7.7</p>
  <p>Added a default category</p>
  <p>Added an option to allow an event to be forced a member of at least 1 category</p>
  <p>Added options of how many years in the past and future you should be able to select</p>
  <p>Progress towards more uptodate API-usage, using templates, actions etc.</p>
  <p>Numerous bugfixes</p>
</li>

<li><p>Version: 0.7.6</p>
  <p>Added column style output for upcominglist and pastlist</p>
  <p>Moved example stylesheet to the stylesheetlist</p>
  <p>Added tagging of events and deletions of tagged ones</p>
  <p>Reworked for use of external actionfiles</p>
  <p>Improved tab-functionaliy and actionmessages</p>
</li>

<li><p>Version: 0.7.5</p>
  <p>Fixed a lot of openbasedir-issues</p>

</li>

<li><p>Version: 0.7.4</p>
  <p>Fixed hardcoded length of title input field</p>
  <p>Fixed some missing localization</p>
  <p>Removed support for pretty urls (it was not working, as some parameters were missing, and putting them in would have made the urls unpretty anyways</p>

  <p>Updated permissions model.  Now need \'Modify Templates\' permission to modify the templates, and \'Modify Site Preferences\' permission to adjust the preferences.</p>

</li>
<li><p>Version: 0.7.3</p>
    <p>Added Minimum CMS Version</p>
    <p>Added the pastlist option</p>
</li>
<li><p>Version: 0.7.2</p>
    <p>CMS 1.0 compatiblity</p>
    <p>Split out into numerous files for better memory efficiency</p>
    <p>Introduced references where necessary to improve memory efficiency</p>
    <p>Added functions to allow for talking with this module via other modules</p>
    <p>Added events</p>
    <p>Improved security and reduced memory footprint</p>
</li>
<li><p>Version: 0.7 stable</p>
    <p>Fixed problem with broken month list on 31st of each month;</p>
    <p>Fixed problem with Calendar showing in the menu for unauthorized admin users.</p>
</li>
<li><p>Version: 0.7beta3</p>
    <p>Added the yearlist view option to list all events in the year. Acts like the list option.</p>
</li>
<li><p>Version: 0.7beta2</p>
    <p>Added the reverse parameter to show events in reverse chronological order.</p>
</li>
<li><p>Version: 0.7beta1</p>
    <p>Added navigation in the list view, fixed problem with events not showing up in the list view.</p>
</li>
<li><p>Version: 0.7alpha2</p>
    <p><ul>
       <li>Bug fix: include last day of the month!</li>
       <li>Bug fix: template use of $table_id should have {} around it.</li>
       <li>Include icon for content page.</li>
       <li>Whitespace changes - trailing spaces and tabs/space tidy up.</li>
       <li>Make default templates XHTML 1.0 Transitional compliant.</li>
    </ul></p>
</li>
<li><p>Version: 0.7alpha1</p>
    <p>Complete rewrite to fit into 0.10.x better.</p>
    <p>Support language for day and month names</p>
    <p>Use smarty templates for controlling the display.</p>
    <p>Rewrite the SQL used to select the events to hopefully be more maintainable.</p>
    <p><strong>Note</strong> that the language files are not fully updated for this version!</p>
</li>
<li><p>Version: 0.6.1</p>
    <p>More fixes for multi-day event on calendar. Added new parameter "time_format" so we can make the display of a single day event with a start and stop time look better. Change de_DE\'s "to" to "bis" as per Mordran\'s post on the boards.</p>
</li>
<li><p>Version: 0.6</p>
   <p>Fix event display so that if the end date is not set, we don\'t display "to".</p>
   <p>Filter by category when displaying an upcominglist.</p>
   <p>Fix End date setting that was off by one.</p>
   <p>Fix odd behaviour of year when transitioning from Jan to Dec or Dec to Jan in the calendar view.</p>
   <p>Support mutli-day events in the calendar view.</p>
</li>
<li><p>Version: 0.5</p>
    <p>Fix the drop down list for end date year. Fix DE translation of "Return" (thanks Piratos!).</p>
    <p>Fix spacing around "to" (thanks Greg!). Add Danish and Dutch translations courtesy of board members esmann and dont.</p>
</li>
<li><p>Version: 0.4</p>
    <p>Support for language translations. Default to a NULL end date. Improved the help information.</p>
    <p>Display upcoming events in the correct order! Other minor bug fixes.</p>
</li>
<li><p>Version: 0.3</p>
    <p>Initial support for "From" and "To" dates for events. Ability to filter admin list of events by category.</p>
</li>
<li><p>Version: 0.2</p>
    <p>New display option: "upcominglist". Also many bugfixes!</p>
</li>
<li><p>Version: 0.1</p>
    <p>Initial release.</p>
</li>
</ul>
