<ul>
<li>Version 1.1.7 - January 31st, 2010
	<ul>
		<li>Included match report per match;</li>
		<li>New link per match to show report upon request of visitor using $entry->matchreport. 
		Column title is in variable: $titlematchreport;</li>
		<li>New page with match report. It has the heading of a match as well</li>
		<li>Match stats can show the report. Use $matchreporttitle and $matchreport as smarty variables;</li>
		<li>Define a couple of arrays so they are not shown as errors in the backend.</li>
	</ul>
</li>
<li>Version 1.1.6 - September 26th, 2008
	<ul>
		<li>Option to toggle if statistics are to be seen on front end.</li>
		<li>New template type 'Stats' introduced.</li>
		<li>Penalty cards and period related fields added to association.</li>
		<li>New front end parameter display to show team members.</li>
		<li>Selection parameters on the match display are based upon previous usage.</li> 
		<li>Introduction of members that can be linked to a team.</li>
		<li>Additional parameter in options part to select where members are to be derived from.</li>
		<li>Security of options now set to Modify TeamSportScores. Maintenance in backend had Use TeamSportScores authorization, is now Modify TeamSportScores.
		<li>You may have to adjust security for non administrators.</li>
		<li>Front end: added parm to show venue location or not.</li>
		<li>Template_id was shown in front-end (removed)</li>
	</ul>
<li>Version 1.1.5 - February 1st, 2008<br>
	<ul>
		<li>Front end: multiple parameters added. Heading on league added on matches tab. Helptext updated with regards to parameter usage.</li>
		<li>Multiple templates can now be stored and used on front end.</li>
	</ul>
<li>Version 1.1.4 - January 30st, 2008
	<ul>
		<li>Leagues introduced. Season removed from matches and league included. Default values on options tab.</li>
		<li>Filter and sorting criteria on matches.</li>
	</ul>
<li>Version 1.1.3 - January 22nd, 2008
	<ul>
		<li>Bug on end date solved. New front end parameter team added. Per match select team or manually enter its name.
		<li>Update to translation file. Bug 'Use of undefined constant' solved.</li>
	</ul>
<li>Version 1.1.2 - January 20th, 2008
	<ul>
		<li>Associations, Clubs, Teams and Seasons have been added. Connection between Matches and Seasons has been made.</li>
	</ul>
<li>Version 1.0 - January 9th 2008
	<ul>
		<li>Initial Release.</li>
  </ul>
</li>
</ul>